//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeItems
    {
        public int Id { get; set; }
        public Nullable<int> OrderBikeId { get; set; }
        public Nullable<int> BikeId { get; set; }
        public Nullable<System.DateTime> StartRent { get; set; }
        public Nullable<System.DateTime> FinishRent { get; set; }
        public Nullable<decimal> Pledqe { get; set; }
        public Nullable<decimal> PriceRent { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual OrderBike OrderBike { get; set; }
    }
}
